# Generated by Django 4.2.5 on 2023-10-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('question1', models.CharField(max_length=255)),
                ('question2', models.CharField(max_length=255)),
                ('question3', models.CharField(max_length=255)),
                ('call_time', models.TimeField()),
                ('recording_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'myphone',
            },
        ),
    ]
